### PR TITLE
cleanup for haxe branch

### PR DESCRIPTION
**Pull request by serjek**
updated extern and nodejs lib
removed redundant libs
code formatting
added explicit ES6 flag to build

### CODE REVIEW

**Comment by endel** [comment]
Awesome, thanks a lot @serjek! ❤️

**Comment by endel** [comment]
Hey @serjek, maybe some of the `tink` modules is actually necessary? I've just tried it and I'm having this error now:

```
 $ npm run compile

> my-app@1.0.0 compile /Users/endel/projects/colyseus/my-colyseus-app
> haxe build.hxml

/Users/endel/haxe/haxe_libraries/hxnodejs/6.9.1/github/38bdefd853f8d637ffb6e74c69ccaedc01985cac/src/js/node/net/Socket.hx:27: characters 8-20 : Type not found : js.lib.Error
```

This error is happening:

```
src/js/node/net/Socket.hx:27: characters 8-20 : Type not found : js.lib.Error
```

**Comment by serjek** [comment]
haha, my bad. I'm using [nightly](http://build.haxe.org/builds/haxe/) haxe build. Let me find the solution with normal rc2...

**Comment by endel** [comment]
oh 😅 I'm using `4.0.0-rc.2+77068e1`

**Comment by serjek** [comment]
so it's like they are revising js.lib package. I reverted hxnodejs version to whatever is current in haxelib, and it compiles now. let me update the branch.

**Pull request merged**
